name: global-country-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - notebook
  - scipy
  - scikit-learn
  - geopandas
  - folium
  - pathlib
  - pytest